#!/usr/bin/env zsh

# https://github.com/apple/swift-format
# brew install swift-format

swift format --in-place --recursive --color-diagnostics ./
#swift-format lint --recursive --color-diagnostics ./


# https://github.com/realm/SwiftLint
# brew install swiftlint

swiftlint --fix --format .

